import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import AppLayout from "../components/AppLayout";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <h1>
          <a href="google.com">TEst</a>
        </h1>
      </AppLayout>
    </>
  );
}
